"use strict";

(() => {
  const qs = (selector, root = document) => root.querySelector(selector);
  const qsa = (selector, root = document) => [...root.querySelectorAll(selector)];
  const readArray = (key) => { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } };
  const writeArray = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const today = new Date();
  const dateKey = (date = new Date()) => date.toISOString().slice(0, 10);
  const escapeText = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
  const formatDate = (value, options = { weekday: 'short', month: 'short', day: 'numeric' }) => new Date(`${value}T00:00:00`).toLocaleDateString('en-KE', options);
  const formatMonth = (value) => new Date(`${value}T00:00:00`).toLocaleDateString('en-KE', { month: 'short', day: 'numeric' });
  const hash = (value) => { let result = 2166136261; for (const character of value) { result ^= character.charCodeAt(0); result = Math.imul(result, 16777619); } return (result >>> 0).toString(16); };

  function createFormController() {
    const dialog = document.createElement('div'); dialog.className = 'pp-dialog'; dialog.setAttribute('aria-hidden', 'true');
    const card = document.createElement('form'); card.className = 'pp-dialog-card'; card.noValidate = true;
    const close = document.createElement('button'); close.type = 'button'; close.className = 'pp-dialog-close'; close.textContent = '×'; close.setAttribute('aria-label', 'Close form');
    const eyebrow = document.createElement('p'); eyebrow.className = 'pp-eyebrow';
    const heading = document.createElement('h3');
    const description = document.createElement('p'); description.className = 'pp-card-description';
    const fields = document.createElement('div'); fields.className = 'pp-fields';
    const error = document.createElement('p'); error.className = 'pp-dialog-error'; error.setAttribute('role', 'alert');
    const actions = document.createElement('div'); actions.className = 'pp-dialog-actions';
    const cancel = document.createElement('button'); cancel.type = 'button'; cancel.className = 'pp-button secondary'; cancel.textContent = 'Cancel';
    const submit = document.createElement('button'); submit.type = 'submit'; submit.className = 'pp-button';
    actions.append(cancel, submit); card.append(close, eyebrow, heading, description, fields, error, actions); dialog.append(card); document.body.append(dialog);
    let active = null;

    const closeForm = () => { dialog.classList.remove('open'); dialog.setAttribute('aria-hidden', 'true'); active = null; error.textContent = ''; };
    const renderField = (field, value) => {
      const label = document.createElement('label'); label.className = 'pp-field'; const name = field.name;
      const title = document.createElement('span'); title.textContent = field.label; label.append(title);
      let control;
      if (field.type === 'textarea') { control = document.createElement('textarea'); control.rows = field.rows || 4; }
      else if (field.type === 'select') { control = document.createElement('select'); (field.options || []).forEach((option) => { const node = document.createElement('option'); node.value = typeof option === 'string' ? option : option.value; node.textContent = typeof option === 'string' ? option : option.label; control.append(node); }); }
      else { control = document.createElement('input'); control.type = field.type || 'text'; }
      control.name = name; control.value = value ?? field.value ?? ''; if (field.placeholder) control.placeholder = field.placeholder; if (field.required) control.required = true; if (field.min !== undefined) control.min = field.min; if (field.max !== undefined) control.max = field.max; if (field.step !== undefined) control.step = field.step; if (field.maxlength) control.maxLength = field.maxlength; label.append(control); return label;
    };
    const openForm = (config) => { active = config; eyebrow.textContent = config.eyebrow || 'Dashboard update'; heading.textContent = config.title; description.textContent = config.description || ''; submit.textContent = config.submitLabel || 'Save'; error.textContent = ''; fields.replaceChildren(); const values = config.values || {}; config.fields.forEach((field) => fields.append(renderField(field, values[field.name]))); dialog.classList.add('open'); dialog.setAttribute('aria-hidden', 'false'); requestAnimationFrame(() => fields.querySelector('input,textarea,select')?.focus()); };
    card.addEventListener('submit', (event) => { event.preventDefault(); if (!active || !card.reportValidity()) return; const values = Object.fromEntries(new FormData(card).entries()); const problem = active.validate?.(values); if (problem) { error.textContent = problem; return; } active.save(values); closeForm(); active.success && window.setTimeout(() => window.dispatchEvent(new CustomEvent('pp-toast', { detail: active.success })), 20); active.reload === false || window.location.reload(); });
    close.addEventListener('click', closeForm); cancel.addEventListener('click', closeForm); dialog.addEventListener('click', (event) => { if (event.target === dialog) closeForm(); }); document.addEventListener('keydown', (event) => { if (dialog.classList.contains('open') && event.key === 'Escape') closeForm(); });
    return openForm;
  }

  const openPassForm = createFormController();

  function getUpcomingExams() { return readArray('examEntries').filter((item) => /^\d{4}-\d{2}-\d{2}$/.test(item.date)).sort((a, b) => a.date.localeCompare(b.date)); }
  function getVisibleUnits() { return qsa('#unitList > div').map((row) => ({ code: row.querySelector('span')?.textContent.trim() || '', name: row.querySelector('strong')?.textContent.trim() || '', lecturer: row.querySelector('small')?.textContent.split('·')[0].trim() || '' })).filter((item) => item.code || item.name); }

  function buildStudyPlan() {
    const exams = getUpcomingExams(); const units = getVisibleUnits(); const slots = []; const cursor = new Date(today);
    for (let offset = 0; offset < 24 && slots.length < 12; offset += 1) { const day = new Date(cursor); day.setDate(cursor.getDate() + offset); const weekday = day.getDay(); if ([2, 4].includes(weekday)) continue; slots.push({ date: dateKey(day), duration: [0, 6].includes(weekday) ? 120 : 90 }); }
    const focus = ['Review lecture notes', 'Create a one-page summary', 'Attempt a past paper', 'Active recall and flashcards'];
    const blocks = slots.map((slot, index) => { const exam = exams.find((item) => item.date >= slot.date) || exams[index % Math.max(exams.length, 1)]; const unit = units.find((item) => item.code === exam?.code) || units[index % Math.max(units.length, 1)] || { code: exam?.code || 'Study block', name: exam?.name || 'Choose a unit', lecturer: '' }; return { id: `${slot.date}-${unit.code}-${index}`, date: slot.date, duration: slot.duration, code: unit.code, title: unit.name, lecturer: unit.lecturer, focus: focus[index % focus.length], done: false }; });
    const signature = exams.map((item) => `${item.code}:${item.date}`).join('|'); const plan = { generatedAt: dateKey(), signature, blocks, note: 'Tuesday and Thursday are protected for attachment searches.' }; localStorage.setItem('autoStudyPlan', JSON.stringify(plan)); return plan;
  }

  function renderStudyPlanner() {
    if (qs('#focusPlan')) { qs('#autoStudyPlanner')?.remove(); return; }
    const host = qs('#studyTools'); if (!host) return;
    let plan = null; try { plan = JSON.parse(localStorage.getItem('autoStudyPlan') || 'null'); } catch { plan = null; }
    const signature = getUpcomingExams().map((item) => `${item.code}:${item.date}`).join('|'); if (!plan?.blocks?.length || plan.signature !== signature) plan = buildStudyPlan();
    let card = qs('#autoStudyPlanner'); if (!card) { card = document.createElement('article'); card.id = 'autoStudyPlanner'; card.className = 'pp-card'; host.append(card); }
    const done = plan.blocks.filter((item) => item.done).length; card.innerHTML = `<div class="pp-heading"><div><p class="pp-eyebrow">Automatic study planner</p><h3>Your next study blocks</h3><p>Built around your exam dates, 90–120 minute sessions, and Tuesday/Thursday attachment searches.</p></div><button type="button" class="pp-button" data-pp-regenerate>Regenerate</button></div><div class="pp-summary"><span class="pp-chip"><strong>${done}/${plan.blocks.length}</strong> blocks complete</span><span class="pp-chip"><strong>${plan.blocks.filter((item) => item.date === dateKey()).length}</strong> for today</span><span class="pp-chip">Tue + Thu protected for attachment</span></div><div class="pp-plan-list">${plan.blocks.map((item) => `<label class="pp-plan-row ${item.done ? 'done' : ''}"><input type="checkbox" data-pp-plan-id="${escapeText(item.id)}" ${item.done ? 'checked' : ''}><span class="pp-plan-date">${escapeText(formatMonth(item.date))}<br>${item.duration} min</span><span class="pp-plan-copy"><strong>${escapeText(item.code)} · ${escapeText(item.title)}</strong><small>${escapeText(item.focus)}${item.lecturer ? ` · ${escapeText(item.lecturer)}` : ''}</small></span><span class="pp-plan-focus">${item.date === dateKey() ? 'TODAY' : ''}</span></label>`).join('')}</div>`;
    card.querySelector('[data-pp-regenerate]').addEventListener('click', () => { buildStudyPlan(); renderStudyPlanner(); }); card.querySelectorAll('[data-pp-plan-id]').forEach((input) => input.addEventListener('change', () => { const current = JSON.parse(localStorage.getItem('autoStudyPlan') || '{}'); const block = current.blocks?.find((item) => item.id === input.dataset.ppPlanId); if (block) block.done = input.checked; localStorage.setItem('autoStudyPlan', JSON.stringify(current)); renderStudyPlanner(); }));
  }

  function renderTodayCommand() {
    const home = qs('#home'); if (!home || qs('#todayCommandCenter')) return; const card = document.createElement('div'); card.id = 'todayCommandCenter'; card.className = 'today-command-card'; home.querySelector('.topbar')?.after(card);
    const plan = (() => { try { return JSON.parse(localStorage.getItem('autoStudyPlan') || '{}'); } catch { return {}; } })(); const nextStudy = plan.blocks?.find((item) => !item.done); const exam = getUpcomingExams()[0]; const todayName = today.toLocaleDateString('en-KE', { weekday: 'long' });
    card.innerHTML = `<div class="pp-heading"><div><p class="pp-eyebrow">Today command center</p><h3>${escapeText(todayName)} · one gentle plan</h3><p>See the next useful move without scanning the whole dashboard.</p></div><a class="pp-button" href="#autoStudyPlanner">Open study plan</a></div><div class="today-command-grid"><div class="today-command-item"><span>Next study move</span><strong>${escapeText(nextStudy?.code || 'Choose a unit')}</strong><small>${escapeText(nextStudy?.focus || 'Generate your study plan below')}</small></div><div class="today-command-item"><span>Next exam</span><strong>${escapeText(exam?.code || 'Dates pending')}</strong><small>${exam ? `${formatMonth(exam.date)} · ${escapeText(exam.time || 'Time to confirm')}` : 'Add the official date when ready'}</small></div><div class="today-command-item"><span>Attachment rhythm</span><strong>Tuesday + Thursday</strong><small>Search placements on those days</small></div><div class="today-command-item"><span>Work focus</span><strong>${escapeText(localStorage.getItem('dailyFocus') || 'Set one focus')}</strong><small>Keep work contained around school</small></div></div>`;
  }

  function renderAttachmentPlanner() {
    const host = qs('#careerTracker .career-grid'); if (!host || qs('#attachmentPlanner')) return; const card = document.createElement('article'); card.id = 'attachmentPlanner'; card.className = 'attachment-planner'; host.after(card);
    const checks = (() => { try { return JSON.parse(localStorage.getItem('attachmentSearchChecks') || '{}'); } catch { return {}; } })(); const dates = []; const cursor = new Date(today); for (let offset = 0; offset < 8; offset += 1) { const day = new Date(cursor); day.setDate(cursor.getDate() + offset); if ([2, 4].includes(day.getDay())) dates.push(dateKey(day)); }
    const render = () => { card.innerHTML = `<div class="pp-heading"><div><p class="pp-eyebrow">Attachment search rhythm</p><strong>Keep Tuesday and Thursday visible.</strong></div><button type="button" class="pp-button secondary" data-pp-attachment-note>Add search note</button></div><div class="attachment-rows">${dates.map((date) => `<label class="attachment-row"><input type="checkbox" data-attachment-date="${date}" ${checks[date] ? 'checked' : ''}><span><strong>${formatDate(date)}</strong><small>Search placement sites, call, or follow up</small></span><button type="button" data-attachment-note="${date}">Note</button></label>`).join('')}</div>`; card.querySelectorAll('[data-attachment-date]').forEach((input) => input.addEventListener('change', () => { checks[input.dataset.attachmentDate] = input.checked; localStorage.setItem('attachmentSearchChecks', JSON.stringify(checks)); })); card.querySelectorAll('[data-attachment-note]').forEach((button) => button.addEventListener('click', () => openPassForm({ title: 'Add attachment search note', description: 'Record a site, contact, follow-up, or question for your Tuesday/Thursday search.', fields: [{ name: 'note', label: 'Search note', type: 'textarea', rows: 4, required: true, maxlength: 500 }], submitLabel: 'Save note', success: 'Attachment note saved.', save: (values) => { const notes = readArray('attachmentSearchNotes'); notes.push({ date: button.dataset.attachmentNote || dateKey(), text: values.note }); writeArray('attachmentSearchNotes', notes.slice(-100)); } }))); }; render();
  }

  function decorateExams() { const list = qs('#examList'); if (!list) return; const exams = readArray('examEntries'); qsa(':scope > div', list).forEach((row) => { if (row.querySelector('[data-pp-exam-actions]')) return; const code = row.querySelector('.exam-code')?.textContent.trim(); const item = exams.find((entry) => entry.code === code); if (!item) return; const actions = document.createElement('div'); actions.className = 'exam-row-actions'; actions.dataset.ppExamActions = 'true'; actions.innerHTML = '<button type="button" data-pp-exam-edit>Edit</button><button type="button" data-pp-exam-delete>Delete</button>'; row.querySelector('section')?.append(actions); actions.querySelector('[data-pp-exam-edit]').addEventListener('click', () => openPassForm({ title: 'Edit exam details', description: 'Keep the official exam information together.', submitLabel: 'Save exam', fields: [{ name: 'code', label: 'Unit code', required: true, maxlength: 30 }, { name: 'name', label: 'Unit or exam name', required: true, maxlength: 180 }, { name: 'date', label: 'Exam date', type: 'date', required: true }, { name: 'time', label: 'Time', required: true, maxlength: 80 }, { name: 'venue', label: 'Venue', maxlength: 160 }, { name: 'lecturer', label: 'Lecturer', maxlength: 160 }, { name: 'classYear', label: 'Class / year', maxlength: 100 }], values: item, save: (values) => { const index = exams.indexOf(item); exams[index] = { ...item, ...values }; writeArray('examEntries', exams); } })); actions.querySelector('[data-pp-exam-delete]').addEventListener('click', () => { if (!confirm(`Delete ${item.code} exam entry?`)) return; writeArray('examEntries', exams.filter((entry) => entry !== item)); window.location.reload(); }); }); }

  function decorateStudyItems() { const list = qs('#studyList'); if (!list) return; const saved = readArray('schoolStudyItems'); qsa('.saved-custom-row', list).forEach((row, index) => { if (row.querySelector('.study-row-actions')) return; const item = saved[index]; if (!item) return; const actions = document.createElement('div'); actions.className = 'study-row-actions'; actions.innerHTML = '<button type="button" data-study-edit>Edit</button><button type="button" data-study-delete>Delete</button>'; row.append(actions); actions.querySelector('[data-study-edit]').addEventListener('click', () => openPassForm({ title: 'Edit study item', fields: [{ name: 'value', label: 'Study topic', required: true, maxlength: 240 }, { name: 'meta', label: 'Schedule or note', maxlength: 240 }], values: item, submitLabel: 'Save item', save: (values) => { saved[index] = { ...item, ...values }; writeArray('schoolStudyItems', saved); } })); actions.querySelector('[data-study-delete]').addEventListener('click', () => { saved.splice(index, 1); writeArray('schoolStudyItems', saved); window.location.reload(); }); }); }

  function attachPrivacyLock() {
    const tools = qs('.backup-tools'); if (!tools || qs('#ppPrivacyButton')) return; const button = document.createElement('button'); button.id = 'ppPrivacyButton'; button.type = 'button'; button.className = 'pp-button'; const update = () => { button.textContent = localStorage.getItem('privacyPinHash') ? 'Lock dashboard' : 'Set privacy PIN'; }; update(); tools.append(button); button.addEventListener('click', () => { if (!localStorage.getItem('privacyPinHash')) { openPassForm({ title: 'Set a private PIN', description: 'This is a local privacy barrier for your device. It is not an online account password.', fields: [{ name: 'pin', label: 'PIN', type: 'password', required: true, minlength: 4, maxlength: 24 }, { name: 'confirm', label: 'Confirm PIN', type: 'password', required: true, minlength: 4, maxlength: 24 }], submitLabel: 'Set PIN', success: 'Privacy PIN saved.', save: (values) => { if (values.pin !== values.confirm || values.pin.length < 4) return; localStorage.setItem('privacyPinHash', hash(values.pin)); sessionStorage.setItem('ppUnlocked', 'true'); }, reload: false }); } else showLockScreen(); });
  }

  function showLockScreen() { if (qs('#ppPrivacyLock')) return; const overlay = document.createElement('div'); overlay.id = 'ppPrivacyLock'; overlay.className = 'pp-lock'; overlay.innerHTML = '<div class="pp-lock-card"><p class="pp-eyebrow">Private dashboard</p><h2>Welcome back, Charry.</h2><p>Your journal stays on this device. Enter your PIN to continue.</p><form><input type="password" aria-label="Privacy PIN" placeholder="Enter PIN" required><button class="pp-button" type="submit">Unlock</button><small class="pp-lock-error"></small></form></div>'; document.body.append(overlay); overlay.querySelector('input').focus(); overlay.querySelector('form').addEventListener('submit', (event) => { event.preventDefault(); const input = overlay.querySelector('input'); if (hash(input.value) === localStorage.getItem('privacyPinHash')) { sessionStorage.setItem('ppUnlocked', 'true'); overlay.remove(); } else { overlay.querySelector('.pp-lock-error').textContent = 'That PIN did not match.'; input.select(); } }); }

  function attachDeviceCard() { const host = qs('#dataManagement .data-management-card'); if (!host || qs('#ppDeviceCard')) return; const card = document.createElement('div'); card.id = 'ppDeviceCard'; card.className = 'pp-device-card'; let installEvent = null; const render = () => { card.innerHTML = `<div><strong>${navigator.onLine ? 'Online and ready' : 'Offline mode'}</strong><small>${navigator.onLine ? 'Your entries still save locally on this device.' : 'The dashboard continues working without internet.'} Install it from your browser menu for quicker phone access.</small></div><button type="button" class="pp-button">Install guide</button>`; card.querySelector('button').addEventListener('click', async () => { if (installEvent) { installEvent.prompt(); await installEvent.userChoice; installEvent = null; return; } alert('On your phone, open the browser menu and choose Add to Home screen or Install app.'); }); }; host.append(card); render(); window.addEventListener('online', render); window.addEventListener('offline', render); window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); installEvent = event; render(); }); }

  function attachMonthlyReview() { const host = qs('#monthlySummary'); if (!host || qs('#ppMonthlyReview')) return; const card = document.createElement('div'); card.id = 'ppMonthlyReview'; card.className = 'pp-monthly-review'; const month = dateKey().slice(0, 7); const study = readArray('studySessions').filter((item) => String(item.date).startsWith(month)); const minutes = study.reduce((sum, item) => sum + (Number(String(item.duration || '').match(/[0-9.]+/)?.[0]) || 0), 0); const content = readArray('contentIdeas').filter((item) => String(item.createdAt || '').startsWith(month)).length + readArray('pipelinePosts').filter((item) => String(item.createdAt || '').startsWith(month)).length; const attachment = Object.entries(JSON.parse(localStorage.getItem('attachmentSearchChecks') || '{}')).filter(([key, value]) => key.startsWith(month) && value).length; const expenses = readArray('expenseLedger').filter((item) => String(item.date || '').startsWith(month)).reduce((sum, item) => sum + Number(item.amount || 0), 0); card.innerHTML = `<p class="pp-eyebrow">Monthly review</p><h3>Notice what moved.</h3><div class="pp-monthly-grid"><div><strong>${content}</strong><small>content pieces captured</small></div><div><strong>${minutes}</strong><small>study minutes</small></div><div><strong>${attachment}</strong><small>attachment searches</small></div><div><strong>KSh ${expenses.toLocaleString()}</strong><small>expenses logged</small></div></div>`; host.append(card); }

  window.addEventListener('load', () => { renderStudyPlanner(); renderTodayCommand(); renderAttachmentPlanner(); decorateExams(); decorateStudyItems(); attachPrivacyLock(); attachDeviceCard(); attachMonthlyReview(); if (localStorage.getItem('privacyPinHash') && sessionStorage.getItem('ppUnlocked') !== 'true') showLockScreen(); const list = qs('#examList'); if (list) new MutationObserver(decorateExams).observe(list, { childList: true, subtree: true }); const study = qs('#studyList'); if (study) new MutationObserver(decorateStudyItems).observe(study, { childList: true, subtree: true }); });
})();
